MQTT_HOSTNAME_KEY = "MQTT_HOSTNAME"
MQTT_PORT_KEY = "MQTT_PORT"
BURST_INTERVAL_KEY = "BURST_INTERVAL_SEC"
DEVICE_NUMBER = "DEVICE_NUMBER"
GOST_TOPIC_PREFIX = "GOST_MQTT_PREFIX"

MQTT_SCRAL_PREFIX = "SCRAL/"