MQTT_SCRAL_PREFIX = "SCRAL/"
DEFAULT_LOG_FORMATTER = "%(asctime)s.%(msecs)04d %(name)-7s %(levelname)s: %(message)s"

DEBUG_KEY = "DEBUG"

MQTT_HOSTNAME_KEY = "MQTT_HOSTNAME"
MQTT_PORT_KEY = "MQTT_PORT"
BURST_INTERVAL_KEY = "BURST_INTERVAL_SEC"
DEVICE_NUMBER_KEY = "DEVICE_NUMBER"
GOST_TOPIC_PREFIX = "GOST_MQTT_PREFIX"

STAGE_NAME_KEY = "STAGE_NAME"
DISTR_STAGE_KEY = "DISTR_STAGE"
LAT_STAGE_KEY = "LAT_STAGE"
LON_STAGE_KEY = "LON_STAGE"
SIGMA_N_S_KEY = "SIGMA_N_S"
SIGMA_E_O_KEY = "SIGMA_E_O"
